# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4
# image: samueldebruyn/debian-git

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          # - npm test
    - step:
        name: Deploy to staging
        deployment: staging   # can be test, staging or production
        # trigger: manual  # uncomment to make manual deployment
        script:
          - echo "Deploying to staging environment"
          - npm install --save-dev git-ftp
          - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://healthypets.siteofdreams.co.uk/
